In [54]:
import numpy as np
import random

In [2]:
arr = np.array([69,420,1,2,3])
arr[0]

69

In [9]:
print(arr.ndim)

1


In [48]:
arr = np.array([[1.2,3.6], [3.4,5], [4.2,7.6]])
arr.ndim

2

In [11]:
arr.dtype

dtype('float64')

In [36]:
arr

array([[1.2, 3.6],
       [3.4, 5. ],
       [4.2, 7.6]])

In [37]:
arr.transpose()

array([[1.2, 3.4, 4.2],
       [3.6, 5. , 7.6]])

In [38]:
arr.reshape(3,2)

array([[1.2, 3.6],
       [3.4, 5. ],
       [4.2, 7.6]])

In [40]:
arr.ravel() # print flatten of the array

array([1.2, 3.6, 3.4, 5. , 4.2, 7.6])

In [43]:
arr = arr.ravel()
arr

array([1.2, 3.6, 3.4, 5. , 4.2, 7.6])

In [45]:
arr.min()

1.2

In [46]:
arr.max()

7.6

In [47]:
arr.sum()

25.0

In [49]:
arr.sum(axis=0)

array([ 8.8, 16.2])

In [68]:
arr.sum(axis = random.randint(0,1))

array([ 8.8, 16.2])

In [70]:
np.sqrt(arr)

array([[1.09544512, 1.8973666 ],
       [1.84390889, 2.23606798],
       [2.04939015, 2.75680975]])

In [14]:
arr.itemsize

8

In [16]:
arr.size

6

In [17]:
arr.shape

(3, 2)

In [26]:
arr=np.zeros( (3,4))

In [27]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
arr.reshape((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
arr.transpose()

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones( (3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.arange(1,5)

array([1, 2, 3, 4])

In [22]:
np.arange(1,5,2)  #step of 2

array([1, 3])

In [23]:
np.arange(1,6,2)  #step of 2

array([1, 3, 5])

In [25]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [72]:
# matrix operations
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [73]:
b = np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [74]:
a + b

array([[ 6,  8],
       [10, 12]])

In [75]:
a - b

array([[-4, -4],
       [-4, -4]])

In [76]:
a * b

array([[ 5, 12],
       [21, 32]])

In [79]:
c = np.linalg.inv(a)
c

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [81]:
d = np.matmul(a,c)
d

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [83]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [86]:
data = np.array([15,21, 24, 10, 13, 26, 29, 14], dtype=float)

data[data>=20] = np.nan

data

array([15., nan, nan, 10., 13., nan, nan, 14.])

In [89]:
(a*b).sum()

70

In [93]:
new_arr = np.arange(1,26, dtype=float)
new_arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.])

In [94]:
new_arr.reshape(5,5)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

In [96]:
new_arr[new_arr>=20] = np.nan
new_arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., nan, nan, nan, nan, nan, nan])